project:
  type: book
  output-dir: docs

book:
  title: "Cours_Tests_statistiques"
  author: "Quentin Laval"
  date: "15/01/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    site-url: "https://quentinlaval.github.io/Cours_Tests_statistiques/"
  pdf:
    documentclass: scrreprt

editor: visual

